

server:
  port: 8081 #项目端口
  url: http://192.168.54.39
mybatis-plus:
  mapper-locations: classpath*:mappings/*.xml
  typeAliasesPackage: com.cndatacom.pcc.domain
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性


spring:
  application:
    name: pcc

  datasource:
        url: jdbc:mysql://127.0.0.1:3306/pingcc?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
        username: root
        password: 123456
        filters: log4j,wall,mergeStat

  servlet:
    multipart:
      max-file-size: 100Mb
      max-request-size: 1000Mb

# Redis数据库索引（默认为0）
  redis:
    database: 1
    host: 192.168.54.39
    port: 6379
    password: 123456
    timeout: 100000
    jedis:
      pool:
        max-wait: -1
        max-active: 1000
        min-idle: 2
          
#spring.redis.database=1
# Redis服务器地址
#spring.redis.host=192.168.106.128
# Redis服务器连接端口
#spring.redis.port=6379
# Redis服务器连接密码（默认为空）
#spring.redis.password=cwh
# 连接池最大连接数（使用负值表示没有限制）
#spring.redis.pool.max-active=1000
# 连接池最大阻塞等待时间（使用负值表示没有限制）
#spring.redis.pool.max-wait=-1
# 连接池中的最大空闲连接
#spring.redis.pool.max-idle=10
# 连接池中的最小空闲连接
#spring.redis.pool.min-idle=2
# 连接超时时间（毫秒）
#spring.redis.timeout=0

# 文件上传配置
#spring.http.multipart.maxFileSize=100Mb
#spring.http.multipart.maxRequestSize=1000Mb
